# Workflow for building and deploying a Next.js site from the front folder to GitHub Pages

name: Deploy Next.js site to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Specify your Node.js version

      - name: Install pnpm
        uses: pnpm/action-setup@v2 # Use pnpm action to install pnpm
        with:
          version: '7' # Specify the version of pnpm you want to use

      - name: Install dependencies
        run: cd front && pnpm install # Navigate to front folder and install dependencies

      - name: Build with Next.js
        run: cd front && pnpm run build # Navigate to front folder and build the project

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: front/out # Adjust this if your output folder is different

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
